# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TestDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge',#最新版本需要此模块，否则启动不起来，RN中文网漏掉了
    'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
    'RCTText',
    'ART',
    'RCTAdSupport',
    'RCTGeolocation',
    'RCTImage',
    'RCTActionSheet',
    'RCTPushNotification',
    'RCTSettings',
    'RCTVibration',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTWebSocket', # 这个模块是用于调试功能的
    # 在这里继续添加你所需要的模块
]
    # 如果你的RN版本 >= 0.42.0，则加入下面这行
    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    
    end

  target 'TestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end


